apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-rabbitmq
  template:
    metadata:
      labels:
        app: ecommerce-rabbitmq
    spec:
      containers:
        - name: ecommerce-rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672   # RabbitMQ default port
            - containerPort: 15672   # RabbitMQ management UI port
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-data
