apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: ecommerce-be
spec:
  selector:
    app: ecommerce-be
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 8000
  type: ClusterIP