apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: ecommerce-fe
spec:
  selector:
    app: ecommerce-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP